from pathlib import Path
import json,html
R=Path(__file__).parent
L={'custom':'https://everydayessentials4-orders.webflow.io/','inquiry':'https://everydayessentials4-orders.webflow.io/website-inquiry','onboarding':'https://everydayessentials4-orders.webflow.io/website-client-onboarding','approval':'https://everydayessentials4-orders.webflow.io/website-review-approval','instagram':'https://www.instagram.com/everydayessentials_4/'}
C=['Digital Products','Party & Events','Seasonal Products','Custom Gifts','Business & Branding','Beauty','Memorial Products','Custom Apparel','Done-For-You Etsy Stores','Drinkware','Flags & Banners','Graduation & Prom']
D=['Business Templates','Party & Event Templates','Memorial Templates','Beauty / Nail Designs','Apparel / Shirt Designs','Seasonal Designs','Branding / Social Media Templates','Bundles','Other Digital Downloads']
PAYHIP='https://payhip.com/u17901776742571242620102'
COLLECTIONS={'Digital Products':('digital-products',11),'Party & Events':('party-events',10),'Seasonal Products':('seasonal-products',10),'Custom Gifts':('custom-gifts',2),'Business & Branding':('business-branding',1),'Beauty':('beauty',0),'Memorial Products':('memorial-products',0),'Custom Apparel':('custom-apparel',0),'Done-For-You Etsy Stores':('done-for-you-etsy-stores',0)}
(R/'assets/shop-links.json').write_text(json.dumps({'shopAll':PAYHIP,'categories':{name:({'url':PAYHIP+'/collection/'+COLLECTIONS[name][0],'publiclyVisible':COLLECTIONS[name][1]>0,'listingCount':COLLECTIONS[name][1]} if name in COLLECTIONS else 'PAYHIP_LINK_PENDING') for name in C},'digital':dict.fromkeys(D,'PAYHIP_LINK_PENDING'),'etsyStoreSetup':{'Mini Launch':'https://payhip.com/b/F0wuT','Store Launch':'https://payhip.com/b/Fq8uv','Business Launch':'https://payhip.com/b/QxYnj'}},indent=2))
def a(url,label,cls='button'):
 if not url: return '<span class="coming" role="status">Custom request form coming soon</span>'
 return '<a class="'+cls+'" href="'+url+'"'+(' target="_blank" rel="noopener noreferrer"' if url.startswith('https:') else '')+'>'+label+'</a>'
def card(title,body,link=''):
 return '<article class="card"><h3>'+title+'</h3><p>'+body+'</p>'+link+'</article>'
def cards(items):return '<div class="grid">'+''.join(items)+'</div>'
def section(k,h,content,variant=''):
 return '<section class="section '+variant+'"><div class="wrap"><span class="eyebrow">'+k+'</span><h2>'+h+'</h2>'+content+'</div></section>'
def hero(k,h,p):return '<section class="hero"><div class="wrap"><span class="eyebrow">'+k+'</span><h1>'+h+'</h1><p class="lead">'+p+'</p></div></section>'
def page(path,title,desc,body):
 nav=[('Home','/'),('Shop','/shop/'),('Custom Orders','/custom-orders/'),('Done-For-You Services','/services/'),('About','/about/'),('Contact','/contact/')]
 header='<a class="skip" href="#main">Skip to content</a><div class="topline">CREATIVE PRODUCTS + BUSINESS SERVICES · DFW BASED</div><header><div class="wrap bar"><a class="brand" href="/" aria-label="Everyday Essentials home"><span class="brand-mark"><img src="/assets/everyday-essentials-logo.jpeg" alt=""></span><span class="brand-type">EVERYDAY <span>ESSENTIALS</span></span></a><button id="menu" aria-label="Toggle navigation" aria-expanded="false" aria-controls="nav">Menu ☰</button><nav id="nav" aria-label="Main navigation">'+''.join(a(u,t,'navlink') for t,u in nav)+a('/custom-orders/','Request a Custom Order','button small')+'</nav></div></header>'
 footer='<footer><div class="wrap footergrid"><div><strong>EVERYDAY ESSENTIALS</strong><p>Creative products and practical business services, made with your vision in mind.</p></div><div><b>Explore</b>'+a('/shop/','Shop','footlink')+a('/custom-orders/','Custom Orders','footlink')+a('/services/','Services','footlink')+'</div><div><b>Information</b>'+a('/faq/','FAQ & Policies','footlink')+a('/contact/','Contact & Partnerships','footlink')+a('/current-clients/','Current Clients','footlink')+'</div><div><b>Connect</b>'+a(L['instagram'],'Instagram ↗','footlink')+'</div></div><div class="wrap copyright">© 2026 Everyday Essentials · Woman-owned · Dallas–Fort Worth</div></footer>'
 doc='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+' | Everyday Essentials</title><meta name="description" content="'+html.escape(desc)+'"><meta name="theme-color" content="#27262b"><link rel="canonical" href="https://REPLACE_WITH_DOMAIN/'+path+'"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/site.js"></script></head><body>'+header+'<main id="main">'+body+'</main>'+footer+'</body></html>'
 target=R/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(doc)
home=hero('Everyday Essentials · DFW','Made personal.<br><em>Built for what’s next.</em>','Custom products for the moments that matter. Digital designs for the things you create. Done-for-you services for the business you’re building.')+'<div class="wrap lead-actions">'+a('/shop/','Explore the shop')+a('/services/','Explore business services','button ghost')+'</div>'
home+=section('Start here','One creative home. Two ways to make it yours.',cards([card('Shop products','Browse organized product and digital collections.',a('/shop/','Browse collections')),card('Custom orders','Tell us about a personalized piece for your occasion.',a(L['custom'],'Request a Custom Order')),card('Business services','Websites, Shopify, Etsy, listings, and creative support.',a('/services/','Explore services'))]))
home+=section('Products','Discover what fits your moment.',cards([card('Digital products','Explore business, event, beauty, apparel, seasonal, and bundle categories.',a('/shop/#digital','Explore digital')),card('Custom products','Apparel, gifts, events, memorial pieces, and more.',a(L['custom'],'Start a custom order')),card('Shop categories','Find the right collection without scrolling through hundreds of items.',a('/shop/','Shop categories'))]),'light')
home+=section('Done-for-you','Build your next business move.',cards([card('Website design','A polished web presence shaped around your business.',a('/services/#websites','See packages')),card('Shopify setup','An organized storefront for your own products.',a('/services/#shopify','See packages')),card('Etsy and listings','Launch, refresh, or add listings to your shop.',a('/services/#etsy','See options'))]),'dark')
home+=section('How it works','A simple start for custom requests.',cards([card('01 · Share your idea','Send names, colors, sizes, photos, event details, and your deadline.'),card('02 · Discuss the details','We follow up about scope, quote, and next steps.'),card('03 · Move forward','Once the details are settled, we can start your project.')])+a(L['custom'],'Request a Custom Order'))
home+=section('Why Everyday Essentials','Creativity with a personal touch.','<p class="lead">Woman-owned and based in the Dallas–Fort Worth area, Everyday Essentials brings thoughtful communication and care to projects for individuals, events, and businesses.</p>'+a('/about/','About the business'),'light')
home+=section('Questions','Need a little more information?',a('/faq/','Read the FAQs')+a('/contact/','Contact us','button ghost'))
page('','Creative Products & Business Services','Explore custom products, digital categories, website design, Shopify and Etsy services from Everyday Essentials in DFW.',home)
def shopcard(name,group):
 available=group=='categories' and name in COLLECTIONS and COLLECTIONS[name][1]>0
 description='Browse available designs and products on Payhip.' if available else 'This collection is being prepared.'
 status='Loading collection…' if available else 'Shop link coming soon'
 return '<article class="card shopcard" data-shop-category="'+html.escape(name)+'" data-group="'+group+'"><span class="eyebrow">Collection</span><h3>'+html.escape(name)+'</h3><p>'+description+'</p><div class="shop-action"><span class="coming">'+status+'</span></div></article>'
shop=hero('Shop Everyday Essentials','Find your kind of creative.','Browse by category. Available category buttons take you directly to Payhip for product browsing and checkout. Need personalization? Request a custom order.')
shop+=section('Shop all','See everything currently available.','<p class="lead">Browse all publicly available products directly on Payhip.</p>'+a(PAYHIP,'Shop All on Payhip ↗'),'light')
shop+=section('Shop by category','Products for moments big and small.',cards(shopcard(x,'categories') for x in C))
shop+=section('Digital collection','Ideas ready to make your own.','<div id="digital">'+cards(shopcard(x,'digital') for x in D)+'</div>','light')
shop+=section('Made for you','Need something custom?',a(L['custom'],'Request a Custom Order'),'dark')
page('shop/','Shop Products & Digital Collections','Browse Everyday Essentials product and digital categories, with Payhip checkout for available collections.',shop)
custom=hero('Custom orders','Your idea, made personal.','Custom apparel, celebrations, keepsakes, and memorial pieces begin with your details.')
custom+=section('Begin here','Tell us what you’re imagining.','<p class="lead">Share your names, wording, size, colors, photos, event date, and any inspiration. Include your deadline so we can discuss availability.</p>'+a(L['custom'],'Request a Custom Order'))
custom+=section('Popular requests','What can we create together?',cards([card('Apparel','Personalized outfits, shirts, and school spirit.'),card('Party & events','Details for a celebration that feels like yours.'),card('Memorial products','Thoughtful pieces with your supplied details and photos.'),card('Gifts & keepsakes','Creative gifts with a personal touch.')]),'light')
page('custom-orders/','Custom Orders','Request custom apparel, event products, gifts, and memorial pieces from Everyday Essentials.',custom)
web=[('Simple Website','$250','3–5 business days','1-page fully built business website; up to 4–5 sections; About; up to 3 services; simple contact form; social links; basic on-page SEO; hosting setup; domain connection; SSL setup; 1 revision round; 14-day launch correction period'),('Starter Website','$400','5–7 business days','Full scrolling fully built website; professional navigation; About; full Services section; contact form; social/booking links; testimonials if provided; FAQ if needed; basic on-page SEO; hosting/domain/SSL setup; 1 revision round; 14-day launch correction period'),('Business Website','$700','7–10 business days','Up to 5 pages of your choice; tailored multi-page design; services pages/sections; gallery or portfolio; testimonials; FAQ; Google Maps/location if applicable; custom lead/contact form; basic on-page SEO; sitemap setup; hosting/domain/SSL setup; 2 revision rounds; 14-day launch correction period'),('Premium Website','$1,200','10–15 business days','Up to 8 pages; everything in Business; more tailored visual design; tasteful animations/interactions; larger gallery/portfolio; more detailed forms; Client Editing Dashboard included; more involved migration if applicable; 3 revision rounds; 14-day launch correction period')]
def package(n,price,time,items,badge=''):
 return '<article class="card"><span class="badge">'+(badge or 'Website package')+'</span><h3>'+n+'</h3><strong class="price">Starting at '+price+'</strong><p>Estimated turnaround: '+time+'</p><ul>'+''.join('<li>'+x+'</li>' for x in items.split('; '))+'</ul>'+a(L['inquiry'],'Get Started')+'</article>'
services=hero('Done-for-you services','A stronger presence starts here.','Websites, organized online stores, and practical business support. Explore starting prices, then tell us about your goals.')
services+=section('Website design','Find the right fit for your website.','<div id="websites">'+cards(package(*w,'Most Popular' if w[0]=='Business Website' else '') for w in web)+'</div>')
services+=section('Additional website options','Adapt your next step.',cards([card('Website Redesign · Starting at $600','A modern replacement for an existing site. Final pricing depends on size and complexity. Estimated turnaround: 7–15 business days.',a(L['inquiry'],'Discuss a redesign')),card('Client Editing Dashboard · Starting at $175','Routine updates to hours, phone/email, services, descriptions, prices, photos, testimonials, FAQs, announcements, and social links. Optional with Simple, Starter, and Business; included with Premium.',a(L['inquiry'],'Ask about editing')),card('Portfolio credit','Clients may qualify for a discount if they allow a small “Website by Everyday Essentials” link in the footer.',a(L['inquiry'],'Ask about eligibility'))]),'light')
shopify=[('Mini Shop','$399','Up to 5 products'),('Starter Shop','$599','Up to 10 products'),('Business Shop','$899','Up to 20 products'),('Growth Shop','$1,249','Up to 50 products')]
services+=section('Shopify done-for-you','Your store, set up for you.','<div id="shopify">'+cards('<article class="card"><span class="badge">'+('Most Popular Ecommerce Package' if n=='Business Shop' else 'Shopify package')+'</span><h3>'+n+'</h3><strong class="price">Starting at '+p+'</strong><p>'+d+'</p>'+a(L['inquiry'],'Get Started')+'</article>' for n,p,d in shopify)+'</div><p class="note">Shopify subscription fees, domain costs, paid apps, payment-processing fees, and other third-party fees are paid directly by the client.</p>','dark')
payhip_setup=[
 ('Mini Store','$150','Up to 5 products','Branded storefront, account settings, product upload, basic categories, policy placement and mobile review'),
 ('Starter Store','$250','Up to 10 products','Everything in Mini plus organized collections, product descriptions and basic SEO, and checkout and delivery review'),
 ('Business Store','$400','Up to 20 products','Everything in Starter plus more detailed collection organization, store pages and launch testing'),
 ('Growth Store','$650','Up to 50 products','Everything in Business plus a larger catalog plan, storefront refinement and a post-launch handoff')]
services+=section('Payhip store setup','A clear storefront for your products.','<div id="payhip">'+cards('<article class="card"><span class="badge">'+('Most Popular Payhip Package' if n=='Business Store' else 'Payhip package')+'</span><h3>'+n+'</h3><strong class="price">Starting at '+p+'</strong><p>'+count+'. '+scope+'.</p>'+a(L['inquiry'],'Get Started')+'</article>' for n,p,count,scope in payhip_setup)+'</div><p class="note">You provide your account, product information, files, images, brand assets and policies. Platform fees, domains, paid tools, photography and custom development are separate. Product information must be complete before upload or launch.</p>','light')
services+=section('Done-for-you Etsy store setup','Choose your launch package.','<div id="etsy"></div><p class="lead">Choose your products. We build your Etsy store. </p><p class="lead">Choose eligible product types from the Store Builder Catalog. We set up and organize the Etsy shop within your package scope; you keep ownership of your account and handle Etsy identity, tax, banking, and payment requirements.</p>'+cards([card('Mini Launch · $99','Up to 5 eligible product types. Storefront setup, banner, shop icon/logo treatment, announcement, About, FAQ/policies, sections, complete SEO listings with titles, descriptions, tags, categories, pricing/variations, organization, and launch review.',a(L['inquiry'],'Get Started')),card('Store Launch · $199 · Most Popular','Up to 10 eligible product types. Includes Mini Launch scope plus keyword research, pricing suggestions, applicable digital/Canva/PDF delivery setup, grouping, competitor-positioning review, and final optimization.',a(L['inquiry'],'Get Started')),card('Business Launch · $349','Up to 20 eligible product types. Includes Store Launch scope plus branding consistency, pricing strategy, applicable delivery setup, category organization, cross-selling suggestions, a 30-day action plan, and one post-launch review or adjustment.',a(L['inquiry'],'Get Started')),card('Full Store · $525','Up to 30 eligible product types. Includes Business Launch scope with expanded catalog setup and launch organization for a larger storefront.',a(L['inquiry'],'Get Started'))])+'<p class="note">One selection means one eligible product type. Custom mockups, out-of-catalog work, and extra artwork are separately quoted. No sales or income guarantee. Etsy verification and financial setup stay with the client.</p>'+a(L['inquiry'],'Ask about Etsy setup'),'light')
services+=section('Etsy listing and shop support','Build, add, or refresh.','<div id="other">'+cards([card('Etsy Listing Services · Starting at $15','Prepare and upload complete listings using your supplied product details, images, pricing, variations and files. Final scope depends on listing count.',a(L['inquiry'],'Ask about listings')),card('Etsy Store Refresh / Fix','Review an existing shop, organize sections, improve supplied listing content and fix identified storefront issues. Scope and price quoted after review.',a(L['inquiry'],'Ask about a refresh')),card('Shop Audit · Estimated $40–$60','A focused review with prioritized improvement suggestions. Final scope and quote confirmed before work.',a(L['inquiry'],'Ask about an audit')),card('Product Listing Services','Organized product presentation for an online store, including Payhip or Shopify where appropriate.',a(L['inquiry'],'Discuss products')),card('Business & Branding','Custom brand and marketing support quoted to your brief.',a(L['inquiry'],'Discuss branding'))])+'</div>')
services+=section('Optional add-ons','Add the work your project needs.','<p class="lead">These are starting prices for separately scoped work. For 51 or more products, request a Large Catalog custom quote instead of stacking individual upload fees.</p>'+cards([
 card('Additional products · $15 each','Additional Etsy, Payhip or Shopify product upload when product details and assets are ready.',a(L['inquiry'],'Request product uploads')),
 card('Product creation · Starting at $35/product','For products or listings that still need to be created, beyond uploading supplied material.',a(L['inquiry'],'Discuss product creation')),
 card('Mockups · 5 for $35 / 10 for $65','Additional product mockups; ask for a quote for custom artwork or complex scenes.',a(L['inquiry'],'Request mockups')),
 card('Website additions','Additional revision: $50. Additional webpage: $100. Additional website section: $50.',a(L['inquiry'],'Discuss your website')),
 card('Brand and dashboard','Simple logo starting at $75. Mini branding kit: $125. Client Editing Dashboard for routine updates: starting at $175, included with Premium Website.',a(L['inquiry'],'Discuss branding')),
 card('Existing store migration · Starting at $150','Move existing products or content from Etsy, Payhip, Shopify or another platform. Final pricing depends on product count and source data quality.',a(L['inquiry'],'Discuss migration')),
 card('Monthly store support · Starting at $149/month','Small updates, listing edits, basic maintenance and technical help. Scope and schedule are confirmed before starting recurring work.',a(L['inquiry'],'Discuss support')),
 card('Rush service · +35%','Available by approval when the schedule and project scope allow it.',a(L['inquiry'],'Ask about rush timing'))
 ]),'light')
services+=section('Custom development','Projects outside the package scope.','<p class="lead">Custom software, databases, portals, membership systems, complex APIs and advanced ecommerce functionality require a separate quote. Projects with 51 or more products require a Large Catalog quote.</p>'+a(L['inquiry'],'Request a custom quote'))
services+=section('Service policies','Clear expectations from the start.',cards([card('Payment','For quoted website and store projects, a 50% deposit begins work and the remaining 50% is due before final launch. Fixed-price Etsy launch packages are paid at checkout when available. Final terms are confirmed before purchase.'),card('Turnaround & revisions','Turnaround begins after payment, content, photos, business information, and account details arrive. Revision rounds depend on the package. Out-of-scope additions may need a new quote.'),card('14-day correction period','For 14 calendar days after launch, we correct technical issues with the website as delivered: broken links, display/layout issues, form errors, and delivered features that do not work. It excludes new content, pages, redesigns, features, client-made or third-party changes, and issues caused after delivery.')])+a(L['inquiry'],'Get Started'),'light')
page('services/','Done-For-You Business Services','Website design, Shopify and Payhip setup, Etsy launch packages, listing services, shop refresh and branding.',services)
about=hero('About us','Creative work with a personal touch.','Everyday Essentials is a woman-owned creative business based in the Dallas–Fort Worth area.')
about+=section('Our approach','Ideas deserve care and clarity.','<p class="lead">Whether you’re celebrating a moment, ordering a personalized piece, or getting your business online, we focus on the details that make the result feel like yours.</p><p>We bring creativity, communication, and a thoughtful process to projects for individuals, events, and businesses.</p>'+a('/contact/','Connect with us'))
about+=section('What we do','One brand. Two creative directions.',cards([card('Products','Custom apparel, gifts, event pieces, and digital categories.',a('/shop/','Explore products')),card('Personalization','A direct request path when your idea calls for your own details.',a(L['custom'],'Start a request')),card('Business services','Websites, Shopify and Etsy support, listings, and more.',a('/services/','Explore services'))]),'light')
page('about/','About Everyday Essentials','Meet Everyday Essentials, a woman-owned DFW creative business for individuals, events, and growing businesses.',about)
contact=hero('Contact','Let’s talk about your idea.','Choose the right form so we can get the details we need to help.')
contact+=section('Get started','The right place for your project.',cards([card('Custom products','Apparel, event pieces, memorial products, and personalized gifts.',a(L['custom'],'Request a Custom Order')),card('Business services','Website design, redesign, Shopify, Etsy, and listings.',a(L['inquiry'],'Get Started')),card('Business partnerships','Tell us about a collaboration or business project.',a(L['inquiry'],'Discuss a partnership'))]))
contact+=section('Keep in touch','Follow the creative process.',a(L['instagram'],'Instagram ↗'),'dark')
page('contact/','Contact & Partnerships','Contact Everyday Essentials for custom orders, business services, and partnership inquiries.',contact)
faqs=[('Where can I shop products?','Choose a collection on the Shop page. Working category links open Payhip for browsing and checkout; pending categories are clearly marked.'),('How do I request a custom order?','Send the details through the Custom Order Request form and we’ll follow up about the quote and next steps.'),('How do business service payments work?','A 50% deposit is due to begin and the remaining 50% is due before final launch and ownership transfer.'),('When does the timeline begin?','After required payment, content, photos, business information, and account details have been received.'),('How many revisions are included?','Revision rounds depend on the package. Out-of-scope additions may need a new quote.'),('What does the 14-day correction period cover?','For 14 calendar days after launch, technical issues with the originally delivered website are corrected, including broken links, layout issues, form errors, and delivered features that do not work. New content, pages, redesigns, features, client-made or third-party changes, and later-caused issues are excluded.'),('Are Shopify fees included?','No. Shopify subscription fees, domain costs, paid apps, payment-processing fees, and other third-party fees are paid directly by the client.')]
faq=hero('FAQ & policies','Good to know before we begin.','Answers about shopping, custom requests, and business services.')
faq+=section('Your questions','Helpful details in one place.','<div class="faq">'+''.join('<details><summary>'+q+'</summary><p>'+v+'</p></details>' for q,v in faqs)+'</div>','light')
page('faq/','FAQ & Service Policies','Answers about shopping, deposits, timelines, revisions, Shopify fees, and the launch correction period.',faq)
clients=hero('Current clients','Your project links, all in one place.','Use these forms when they apply to your active website project.')
clients+=section('Project workflow','Continue your website project.',cards([card('Website Client Onboarding','Share the details and assets needed to begin.',a(L['onboarding'],'Open onboarding')),card('Website Review & Approval','Review your project and submit feedback or approval.',a(L['approval'],'Open review form'))]))
page('current-clients/','Current Clients','Website onboarding and review forms for existing Everyday Essentials clients.',clients)
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://REPLACE_WITH_DOMAIN/'+p+'</loc></url>' for p in ['','shop/','custom-orders/','services/','about/','contact/','faq/','current-clients/'])+'</urlset>')
(R/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://REPLACE_WITH_DOMAIN/sitemap.xml\n')
(R/'_headers').write_text('/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n')
