from pathlib import Path
import json,html,os
R=Path(__file__).parent
SITE_ORIGIN=os.environ.get("SITE_ORIGIN", "").rstrip("/")
def absolute(path): return SITE_ORIGIN+"/"+path if SITE_ORIGIN else ""
L={'custom':'https://everydayessentials4-orders.webflow.io/','inquiry':'https://everydayessentials4-orders.webflow.io/website-inquiry','onboarding':'https://everydayessentials4-orders.webflow.io/website-client-onboarding','approval':'https://everydayessentials4-orders.webflow.io/website-review-approval','instagram':'https://www.instagram.com/everydayessentials_4/','facebook':'https://www.facebook.com/share/16uhWz9tt8/?mibextid=wwXIfr'}
C=['Digital Products','Party & Events','Seasonal Products','Custom Gifts','Business & Branding','Beauty','Memorial Products','Custom Apparel','Done-For-You Etsy Stores','Drinkware','Flags & Banners','Graduation & Prom']
D=['Business Templates','Party & Event Templates','Memorial Templates','Beauty / Nail Designs','Apparel / Shirt Designs','Seasonal Designs','Branding / Social Media Templates','Bundles','Other Digital Downloads']
PAYHIP='https://payhip.com/u17901776742571242620102'
DFY_PAGES={'etsy':PAYHIP+'/done-for-you-etsy-store-launch','payhip':PAYHIP+'/done-for-you-payhip-store-setup','shopify':PAYHIP+'/done-for-you-shopify-store-setup','website':PAYHIP+'/done-for-you-business-websites','redesign':PAYHIP+'/done-for-you-website-redesign'}
GRAD_PRODUCTS={'Graduation Button Templates':'https://payhip.com/b/PsmhH','Graduation Newspaper Templates':'https://payhip.com/b/wdtlV','Graduation Lanyard & ID Badge Templates':'https://payhip.com/b/BVYqT','Graduation Retractable Banner Template':'https://payhip.com/b/ML7KP','Graduation Last Lap Sign Template':'https://payhip.com/b/SBux6','Graduation Ticket Template':'https://payhip.com/b/i1E9L'}
COLLECTIONS={'Digital Products':('digital-products',11),'Party & Events':('party-events',10),'Seasonal Products':('seasonal-products',10),'Custom Gifts':('custom-gifts',2),'Business & Branding':('business-branding',1),'Beauty':('beauty',0),'Memorial Products':('memorial-products',0),'Custom Apparel':('custom-apparel',0),'Done-For-You Etsy Stores':('done-for-you-etsy-stores',0)}
BUNDLES=json.loads((R/'assets/bundles.json').read_text())
BUNDLE_LINKS={bundle['id']:'PAYHIP_LINK_PENDING' for bundle in BUNDLES}
BUNDLE_LINKS['ultimate-255-editable-canva-template-bundle']='https://payhip.com/b/kmDuL'
(R/'assets/shop-links.json').write_text(json.dumps({'shopAll':PAYHIP,'categories':{name:({'url':PAYHIP+'/collection/'+COLLECTIONS[name][0],'publiclyVisible':COLLECTIONS[name][1]>0,'listingCount':COLLECTIONS[name][1]} if name in COLLECTIONS else 'PAYHIP_LINK_PENDING') for name in C},'digital':dict.fromkeys(D,'PAYHIP_LINK_PENDING'),'graduationTemplates':GRAD_PRODUCTS,'bundles':BUNDLE_LINKS,'servicePages':DFY_PAGES,'etsyStoreSetup':{'Mini Launch':'https://payhip.com/b/F0wuT','Store Launch':'https://payhip.com/b/Fq8uv','Business Launch':'https://payhip.com/b/QxYnj'}},indent=2))
def a(url,label,cls='button'):
 if not url: return '<span class="coming" role="status">Custom request form coming soon</span>'
 return '<a class="'+cls+'" href="'+url+'"'+(' target="_blank" rel="noopener noreferrer"' if url.startswith('https:') else '')+'>'+label+'</a>'
def card(title,body,link=''):
 return '<article class="card"><h3>'+title+'</h3><p>'+body+'</p>'+link+'</article>'
def choice(url, eyebrow, name, description):
 return '<a class="choice" href="'+url+'"><span class="badge">'+eyebrow+'</span><strong>'+name+'</strong><span>'+description+'</span><b aria-hidden="true">Explore →</b></a>'
def cards(items):return '<div class="grid">'+''.join(items)+'</div>'
def section(k,h,content,variant=''):
 return '<section class="section '+variant+'"><div class="wrap"><span class="eyebrow">'+k+'</span><h2>'+h+'</h2>'+content+'</div></section>'
def hero(k,h,p):return '<section class="hero"><div class="wrap"><span class="eyebrow">'+k+'</span><h1>'+h+'</h1><p class="lead">'+p+'</p></div></section>'
def page(path,title,desc,body):
 nav=[('Home','/'),('Shop','/shop/'),('Custom Orders','/custom-orders/'),('Done-For-You Services','/services/'),('About','/about/'),('Contact','/contact/')]
 header='<a class="skip" href="#main">Skip to content</a><div class="topline">CREATIVE PRODUCTS + BUSINESS SERVICES · DFW BASED</div><header><div class="wrap bar"><a class="brand" href="/" aria-label="Everyday Essentials home"><span class="brand-mark"><img src="/assets/everyday-essentials-logo.jpeg" alt=""></span><span class="brand-type">EVERYDAY <span>ESSENTIALS</span></span></a><button id="menu" aria-label="Toggle navigation" aria-expanded="false" aria-controls="nav">Menu ☰</button><nav id="nav" aria-label="Main navigation">'+''.join(a(u,t,'navlink') for t,u in nav)+a('/custom-orders/','Request a Custom Order','button small')+'</nav></div></header>'
 footer='<footer><div class="wrap footergrid"><div><strong>EVERYDAY ESSENTIALS</strong><p>Creative products and practical business services, made with your vision in mind.</p></div><div><b>Explore</b>'+a('/shop/','Shop','footlink')+a('/custom-orders/','Custom Orders','footlink')+a('/services/','Services','footlink')+'</div><div><b>Information</b>'+a('/faq/','FAQ & Policies','footlink')+a('/contact/','Contact & Partnerships','footlink')+a('/current-clients/','Current Clients','footlink')+'</div><div><b>Connect</b>'+a(L['instagram'],'Instagram ↗','footlink')+a(L['facebook'],'Facebook ↗','footlink')+'</div></div><div class="wrap copyright">© 2026 Everyday Essentials · Woman-owned · Dallas–Fort Worth</div></footer>'
 seo_title=title if path=='' else title+' | Everyday Essentials'
 url=absolute(path)
 canonical='<link rel="canonical" href="'+html.escape(url,quote=True)+'">' if url else ''
 social='<meta property="og:type" content="website"><meta property="og:site_name" content="Everyday Essentials"><meta property="og:title" content="'+html.escape(seo_title,quote=True)+'"><meta property="og:description" content="'+html.escape(desc,quote=True)+'"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="'+html.escape(seo_title,quote=True)+'"><meta name="twitter:description" content="'+html.escape(desc,quote=True)+'">'
 if url: social+='<meta property="og:url" content="'+html.escape(url,quote=True)+'">'
 schema={'@context':'https://schema.org','@type':'Organization','name':'Everyday Essentials','description':'Small business websites, online store setup and creative products based in Dallas–Fort Worth.'} if path=='' else None
 if schema and url: schema['url']=url
 structured='<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False).replace('</','<\/')+'</script>' if schema else ''
 doc='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(seo_title)+'</title><meta name="description" content="'+html.escape(desc,quote=True)+'"><meta name="theme-color" content="#27262b">'+canonical+social+structured+'<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/site.js"></script></head><body>'+header+'<main id="main">'+body+'</main>'+footer+'</body></html>'
 target=R/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(doc)
home=hero('Everyday Essentials · DFW','Made personal.<br><em>Built for what’s next.</em>','Shop creative products and digital designs, or get help building your business.').replace('class="hero"','class="hero compact-hero"',1)
home+=section('Choose your path','What brings you here?','<div class="choice-grid">'+''.join([choice('/shop/','Products & downloads','Shop Everyday Essentials','Browse available collections on Payhip.'),choice('/services/websites/','Business websites','Website design','See packages and starting prices.'),choice('/services/shopify/','Online stores','Shopify setup','A store built for your products.'),choice('/services/etsy/','Marketplace services','Etsy setup & listings','Launch a shop or improve listings.'),choice('/services/seo/','Search visibility','SEO & Google visibility','Improve your website and local search presence.'),choice('/shop/bundles/','Digital templates','Bundles','Browse the planned bundle catalog and available mega bundle.')])+'</div><div class="home-secondary">'+a(L['custom'],'Request a Custom Order')+a('/services/','Explore all services','button ghost')+'</div>')
home+=section('About Everyday Essentials','Creative work with a personal touch.','<p class="lead">Woman-owned and based in the Dallas–Fort Worth area, we create personalized products and support businesses with practical done-for-you services.</p>'+a('/about/','Meet Everyday Essentials'),'light')
page('','Small Business Websites, Store Setup & SEO | Everyday Essentials','Explore small business website design, website redesign, Etsy and Payhip store setup, and SEO services from Everyday Essentials.',home)
def shopcard(name,group):
 available=group=='categories' and name in COLLECTIONS and COLLECTIONS[name][1]>0
 if available:
  description='Browse available designs and products on Payhip.'
  action=a(PAYHIP+'/collection/'+COLLECTIONS[name][0],'Shop category ↗')
 elif group=='categories' and name=='Graduation & Prom':
  description='Graduation templates are available now. Prom collection links are coming soon.'
  action=a('/shop/graduation-bundles/','Explore graduation templates')
 elif group=='digital' and name=='Bundles':
  description='Browse the digital bundle catalog by theme.'
  action=a('/shop/bundles/','Explore bundles')
 elif group=='categories' and name in ('Custom Apparel','Memorial Products','Drinkware','Flags & Banners'):
  description='Have a personalized piece in mind? Tell us what you need.'
  action=a('/custom-orders/','Custom order details')
 else:
  description='This collection is being prepared.'
  action='<span class="coming">Coming soon</span>'
 return '<article class="card shopcard"><span class="eyebrow">Collection</span><h3>'+html.escape(name)+'</h3><p>'+description+'</p><div class="shop-action">'+action+'</div></article>'
shop=hero('Shop Everyday Essentials','Find your kind of creative.','Browse by category. Available category buttons take you directly to Payhip for product browsing and checkout. Need personalization? Request a custom order.')
shop+=section('Shop all','See everything currently available.','<p class="lead">Browse all publicly available products directly on Payhip.</p>'+a(PAYHIP,'Shop All on Payhip ↗'),'light')
shop+=section('Shop by category','Products for moments big and small.',cards(shopcard(x,'categories') for x in C))
shop+=section('Digital collection','Ideas ready to make your own.','<div id="digital">'+cards(shopcard(x,'digital') for x in D)+'</div>','light')
shop+=section('Digital bundles','Find a set for your next project.','<p class="lead">Explore 40 themed bundles. The existing mega bundle is available now; new listings will be connected as they go live.</p>'+a('/shop/bundles/','Browse bundles')+a('/shop/graduation-bundles/','Graduation templates','button ghost'),'light')
shop+=section('Made for you','Need something custom?',a(L['custom'],'Request a Custom Order'),'dark')
page('shop/','Shop Products & Digital Collections','Browse Everyday Essentials product and digital categories, with Payhip checkout for available collections.',shop)
custom=hero('Custom orders','Your idea, made personal.','Custom apparel, celebrations, keepsakes, and memorial pieces begin with your details.')
custom+=section('Begin here','Tell us what you’re imagining.','<p class="lead">Share your names, wording, size, colors, photos, event date, and any inspiration. Include your deadline so we can discuss availability.</p>'+a(L['custom'],'Request a Custom Order'))
custom+=section('Popular requests','What can we create together?',cards([card('Apparel','Personalized outfits, shirts, and school spirit.'),card('Party & events','Details for a celebration that feels like yours.'),card('Memorial products','Thoughtful pieces with your supplied details and photos.'),card('Gifts & keepsakes','Creative gifts with a personal touch.')]),'light')
page('custom-orders/','Custom Orders','Request custom apparel, event products, gifts, and memorial pieces from Everyday Essentials.',custom)
web=[('Simple Website','$250','3–5 business days','1-page fully built business website; up to 4–5 sections; About; up to 3 services; simple contact form; social links; basic on-page SEO; hosting setup; domain connection; SSL setup; 1 revision round; 14-day launch correction period'),('Starter Website','$400','5–7 business days','Full scrolling fully built website; professional navigation; About; full Services section; contact form; social/booking links; testimonials if provided; FAQ if needed; basic on-page SEO; hosting/domain/SSL setup; 1 revision round; 14-day launch correction period'),('Business Website','$700','7–10 business days','Up to 5 pages of your choice; tailored multi-page design; services pages/sections; gallery or portfolio; testimonials; FAQ; Google Maps/location if applicable; custom lead/contact form; basic on-page SEO; sitemap setup; hosting/domain/SSL setup; 2 revision rounds; 14-day launch correction period'),('Premium Website','$1,200','10–15 business days','Up to 8 pages; everything in Business; more tailored visual design; tasteful animations/interactions; larger gallery/portfolio; more detailed forms; Client Editing Dashboard included; more involved migration if applicable; 3 revision rounds; 14-day launch correction period')]
def package(n,price,time,items,badge=''):
 return '<article class="card"><span class="badge">'+(badge or 'Website package')+'</span><h3>'+n+'</h3><strong class="price">Starting at '+price+'</strong><p>Estimated turnaround: '+time+'</p><ul>'+''.join('<li>'+x+'</li>' for x in items.split('; '))+'</ul></article>'
services=hero('Done-for-you services','What can we help you build?','Choose a service to see packages, starting prices, and what is included.').replace('class="hero"','class="hero compact-hero"',1)
services+=section('Choose your path','Start with what you need.','<div class="choice-grid">'+''.join([choice('/services/websites/','Business websites','Website design & redesign','Fully built business websites and redesigns.'),choice('/services/shopify/','Online stores','Shopify setup','Done-for-you stores for your own products.'),choice('/services/etsy/','Marketplace launch','Etsy stores & listings','Store launch packages and listing support.'),choice('/services/payhip/','Digital storefronts','Payhip setup','An organized Payhip store for your products.'),choice('/services/seo/','Search visibility','SEO & Google visibility','Website SEO and local visibility services.'),choice('/shop/bundles/','Digital templates','Template bundles','Explore the planned bundles and available mega bundle.')])+'</div>')
services+=section('Need some guidance?','Tell us about your project.','<p class="lead">We can help you choose the right starting point and confirm your quote.</p>'+a('/contact/','Ask about business services')+a('/custom-orders/','Custom order information','button ghost'),'light')
page('services/','Website, Store Setup & SEO Services','Explore website design, redesign, Etsy and Payhip setup, Shopify stores, and SEO services for small businesses.',services)
seo=hero('SEO & Google visibility','Help customers find your business.','Improve your online presence with website SEO, local search support and Google visibility services.')
seo+=section('Services','Find the right search support.',cards([card('Website SEO','Review page titles, content, structure and technical issues that affect search visibility.'),card('Local SEO','Improve location relevance and help customers find your services in the areas you actually serve.'),card('Google visibility','Get support with Google Business Profile, keyword research and analytics where applicable.'),card('Ongoing support','Plan continued optimization based on your site, goals and competition.')]),'light')
seo+=section('Get started','Tell us about your website.','<p class="lead">SEO can be a standalone service, even if we did not build your site. Scope and final quote depend on your pages, locations, goals and current website condition.</p>'+a('https://payhip.com/u17901776742571242620102/seo-google-visibility-services','View SEO service details ↗')+a('/contact/','Ask about SEO','button ghost'))
page('services/seo/','SEO & Google Visibility Services','Website SEO, local SEO and Google visibility support for small businesses. Explore standalone services and request a quote.',seo)
websites=hero('Website design','A website for your next chapter.','Explore fully built and functional websites, or ask us to refresh the site you already have.')
websites+=section('Website design','Find the right fit for your website.','<div id="websites">'+cards(package(*w,'Most Popular' if w[0]=='Business Website' else '') for w in web)+'</div>')
websites+=section('Additional website options','Adapt your next step.',cards([card('Website Redesign · Starting at $400','A modern replacement for an existing site. Final pricing depends on size and complexity. Estimated turnaround: 7–15 business days.',),card('Client Editing Dashboard · Starting at $175','Routine updates to hours, phone/email, services, descriptions, prices, photos, testimonials, FAQs, announcements, and social links. Optional with Simple, Starter, and Business; included with Premium.',a('/contact/','Ask about editing')),card('Portfolio credit','Clients may qualify for a discount if they allow a small “Website by Everyday Essentials” link in the footer.',a('/contact/','Ask about eligibility'))]),'light')
websites+=section('Next steps','Start with your goals.','<p class="lead">Tell us about your business, pages, and features. Final scope and pricing are confirmed before work begins.</p>'+a('/contact/','Get a website quote')+a('/services/add-ons/','Explore add-ons','button ghost'),'light')
page('services/websites/','Website Design & Redesign','Compare Everyday Essentials website packages and redesign services, with starting prices and inquiry details.',websites)
shopify=[('Mini Shop','$399','Up to 5 products'),('Starter Shop','$599','Up to 10 products'),('Business Shop','$899','Up to 20 products'),('Growth Shop','$1,249','Up to 50 products')]
shopify_page=hero('Shopify store setup','Your store, ready to grow.','Compare done-for-you Shopify setup packages for your business.')
shopify_page+=section('Shopify done-for-you','Your store, set up for you.','<div id="shopify">'+cards('<article class="card"><span class="badge">'+('Most Popular Ecommerce Package' if n=='Business Shop' else 'Shopify package')+'</span><h3>'+n+'</h3><strong class="price">Starting at '+p+'</strong><p>'+d+'</p></article>' for n,p,d in shopify)+'</div><p class="note">Shopify subscription fees, domain costs, paid apps, payment-processing fees, and other third-party fees are paid directly by the client.</p>','dark')
shopify_page+=section('Start here','Tell us about your products.','<p class="lead">We confirm catalog size, assets, access and the final quote before setup begins.</p>'+a('/contact/','How to get started')+a('/services/add-ons/','Explore add-ons','button ghost'),'light')
page('services/shopify/','Shopify Store Setup','Compare Shopify setup packages from Everyday Essentials, starting at $399.',shopify_page)
payhip_setup=[
 ('Mini Store','$150','Up to 5 products','Branded storefront, account settings, product upload, basic categories, policy placement and mobile review'),
 ('Starter Store','$250','Up to 10 products','Everything in Mini plus organized collections, product descriptions and basic SEO, and checkout and delivery review'),
 ('Business Store','$400','Up to 20 products','Everything in Starter plus more detailed collection organization, store pages and launch testing'),
 ('Growth Store','$650','Up to 50 products','Everything in Business plus a larger catalog plan, storefront refinement and a post-launch handoff')]
payhip_page=hero('Payhip store setup','Give your products a clear home.','Compare done-for-you Payhip setup packages for digital and other products.')
payhip_page+=section('Payhip store setup','A clear storefront for your products.','<div id="payhip">'+cards('<article class="card"><span class="badge">'+('Most Popular Payhip Package' if n=='Business Store' else 'Payhip package')+'</span><h3>'+n+'</h3><strong class="price">Starting at '+p+'</strong><p>'+count+'. '+scope+'.</p></article>' for n,p,count,scope in payhip_setup)+'</div><p class="note">You provide your account, product information, files, images, brand assets and policies. Platform fees, domains, paid tools, photography and custom development are separate. Product information must be complete before upload or launch.</p>','light')
payhip_page+=section('Start here','Organize your next launch.','<p class="lead">Share your products, files and brand assets so we can confirm the right scope.</p>'+a('/contact/','How to get started')+a('/services/add-ons/','Explore add-ons','button ghost'),'light')
page('services/payhip/','Payhip Store Setup','Compare Payhip setup packages from Everyday Essentials, starting at $150.',payhip_page)
etsy_page=hero('Etsy launch & listings','Build an Etsy shop with a clear plan.','Choose a launch package or ask for help improving listings you already have.')
etsy_page+=section('Done-for-you Etsy store setup','Choose your launch package.','<div id="etsy"></div><p class="lead">Choose your products. We build your Etsy store. </p><p class="lead">Choose eligible product types from the Store Builder Catalog. We set up and organize the Etsy shop within your package scope; you keep ownership of your account and handle Etsy identity, tax, banking, and payment requirements.</p>'+cards([card('Mini Launch · Starting at $99','Up to 5 eligible product types. Storefront setup, banner, shop icon/logo treatment, announcement, About, FAQ/policies, sections, complete SEO listings with titles, descriptions, tags, categories, pricing/variations, organization, and launch review.',),card('Store Launch · Starting at $199 · Most Popular','Up to 10 eligible product types. Includes Mini Launch scope plus keyword research, pricing suggestions, applicable digital/Canva/PDF delivery setup, grouping, competitor-positioning review, and final optimization.',),card('Business Launch · Starting at $349','Up to 20 eligible product types. Includes Store Launch scope plus branding consistency, pricing strategy, applicable delivery setup, category organization, cross-selling suggestions, a 30-day action plan, and one post-launch review or adjustment.',),card('Full Store · Starting at $525','Up to 30 eligible product types. Includes Business Launch scope with expanded catalog setup and launch organization for a larger storefront.',)])+'<p class="note">One selection means one eligible product type. Custom mockups, out-of-catalog work, and extra artwork are separately quoted. No sales or income guarantee. Etsy verification and financial setup stay with the client.</p>'+a('/contact/','Ask about Etsy setup'),'light')
etsy_page+=section('Etsy listing and shop support','Build, add, or refresh.','<div id="other">'+cards([card('Etsy Listing Services · Starting at $15','Prepare and upload complete listings using your supplied product details, images, pricing, variations and files. Final scope depends on listing count.',a('/contact/','Ask about listings')),card('Etsy Store Refresh / Fix','Review an existing shop, organize sections, improve supplied listing content and fix identified storefront issues. Scope and price quoted after review.',a('/contact/','Ask about a refresh')),card('Shop Audit · Starting at $40–$60','A focused review with prioritized improvement suggestions. Final scope and quote confirmed before work.',a('/contact/','Ask about an audit')),card('Product Listing Services','Organized product presentation for an online store, including Payhip or Shopify where appropriate.',a('/contact/','Discuss products')),card('Business & Branding','Custom brand and marketing support quoted to your brief.',a('/contact/','Discuss branding'))])+'</div>')
etsy_page+=section('Next steps','Choose your launch path.','<p class="lead">Explore the public service details, then tell us about your products and goals.</p>'+a('/contact/','How to get started')+a('/services/add-ons/','Explore add-ons','button ghost'),'light')
page('services/etsy/','Etsy Store Setup & Listings','Compare Etsy launch packages and listing services from Everyday Essentials.',etsy_page)
addons=hero('Service add-ons','Make the scope fit your project.','Add practical support to a website or store package, or ask about custom development.')
addons+=section('Optional add-ons','Add the work your project needs.','<p class="lead">These are starting prices for separately scoped work. For 51 or more products, request a Large Catalog custom quote instead of stacking individual upload fees.</p>'+cards([
 card('Additional products · $15 each','Additional Etsy, Payhip or Shopify product upload when product details and assets are ready.',a('/contact/','Request product uploads')),
 card('Product creation · Starting at $35/product','For products or listings that still need to be created, beyond uploading supplied material.',a('/contact/','Discuss product creation')),
 card('Mockups · 5 for $35 / 10 for $65','Additional product mockups; ask for a quote for custom artwork or complex scenes.',a('/contact/','Request mockups')),
 card('Website additions','Additional revision: $50. Additional webpage: $100. Additional website section: $50.',a('/contact/','Discuss your website')),
 card('Brand and dashboard','Simple logo starting at $75. Mini branding kit: $125. Client Editing Dashboard for routine updates: starting at $175, included with Premium Website.',a('/contact/','Discuss branding')),
 card('Existing store migration · Starting at $150','Move existing products or content from Etsy, Payhip, Shopify or another platform. Final pricing depends on product count and source data quality.',a('/contact/','Discuss migration')),
 card('Monthly store support · Starting at $149/month','Small updates, listing edits, basic maintenance and technical help. Scope and schedule are confirmed before starting recurring work.',a('/contact/','Discuss support')),
 card('Rush service · +35%','Available by approval when the schedule and project scope allow it.',a('/contact/','Ask about rush timing'))
 ]),'light')
addons+=section('Custom development','Projects outside the package scope.','<p class="lead">Custom software, databases, portals, membership systems, complex APIs and advanced ecommerce functionality require a separate quote. Projects with 51 or more products require a Large Catalog quote.</p>'+a('/contact/','Request a custom quote'))
addons+=section('Service policies','Clear expectations from the start.',cards([card('Payment','For quoted website and store projects, a 50% deposit begins work and the remaining 50% is due before final launch. Fixed-price Etsy launch packages are paid at checkout when available. Final terms are confirmed before purchase.'),card('Turnaround & revisions','Turnaround begins after payment, content, photos, business information, and account details arrive. Revision rounds depend on the package. Out-of-scope additions may need a new quote.'),card('14-day correction period','For 14 calendar days after launch, we correct technical issues with the website as delivered: broken links, display/layout issues, form errors, and delivered features that do not work. It excludes new content, pages, redesigns, features, client-made or third-party changes, and issues caused after delivery.')])+a('/contact/','Get Started'),'light')
page('services/add-ons/','Service Add-Ons & Policies','Starting prices for product uploads, mockups, migration, support and other services.',addons)
def bundle_card(bundle):
 name=html.escape(bundle['name'])
 items=''.join('<li>'+html.escape(item)+'</li>' for item in bundle['plannedContents'])
 url=BUNDLE_LINKS[bundle['id']]
 live=url.startswith('https://payhip.com/')
 price=('Regular price $' if live else 'Planned regular price $')+bundle['regularPrice']
 action=a(url,'View on Payhip ↗') if live else '<span class="coming" role="status">Payhip link coming soon</span>'
 contents='<details class="bundle-contents"><summary>'+('See bundle contents' if live else 'See planned contents')+'</summary><ul>'+items+'</ul></details>'
 return '<article class="card bundle-card"><span class="badge">'+('Available now' if live else 'In preparation')+'</span><h3>'+name+'</h3><strong class="price">'+price+'</strong>'+contents+'<div class="bundle-action">'+action+'</div></article>'
bundles=hero('Digital product bundles','One collection. More ways to create.','Explore the planned template bundles by theme. Each new bundle will link directly to its Payhip listing when it is published.')
mega=next(bundle for bundle in BUNDLES if bundle['category']=='All Templates')
bundles+=section('Available now','The complete template collection.',cards([bundle_card(mega)]),'light')
groups=[]
for category in dict.fromkeys(bundle['category'] for bundle in BUNDLES if bundle['category']!='All Templates'):
 group=[bundle for bundle in BUNDLES if bundle['category']==category]
 groups.append('<details class="bundle-group"><summary><span>'+html.escape(category)+'</span><small>'+str(len(group))+' bundles</small></summary>'+cards(bundle_card(bundle) for bundle in group)+'</details>')
bundles+=section('Browse by theme','Find the right bundle.','<p class="lead">Open a category to see its planned bundles and contents. New checkout links appear as listings go live.</p>'+''.join(groups))
bundles+=section('Graduation templates','Want an individual design now?','<p class="lead">Shop the available graduation templates separately while the themed bundles are being prepared.</p>'+a('/shop/graduation-bundles/','Explore graduation templates'),'light')
page('shop/bundles/','Digital Template Bundles','Browse 40 Everyday Essentials digital template bundles by theme, with Payhip links for available listings.',bundles)
graduation=hero('Graduation digital templates','Make the whole celebration yours.','Browse editable graduation designs for buttons, signs, lanyards, banners and more. Checkout and downloads for available products are handled by Payhip.')
graduation+=section('More than one design?','Explore the bundle catalog.','<p class="lead">Graduation party, fan, shirt, and seller bundles are being prepared. See their planned contents in one place.</p>'+a('/shop/bundles/','Browse graduation bundles'),'light')
graduation+=section('Available now','Shop graduation templates individually.',cards(card(name,'Editable digital template. See the Payhip listing for the exact files and usage details.',a(url,'View on Payhip ↗')) for name,url in GRAD_PRODUCTS.items()))
graduation+=section('Need a finished product?','Have us make something personal.','<p class="lead">If you want a custom physical graduation item, share your names, colors, photos and event date through the order form.</p>'+a(L['custom'],'Request a Custom Order'),'light')
page('shop/graduation-bundles/','Graduation Digital Templates & Bundles','Shop editable graduation templates and explore the upcoming graduation bundle from Everyday Essentials.',graduation)
about=hero('About us','Creative work with a personal touch.','Everyday Essentials is a woman-owned creative business based in the Dallas–Fort Worth area.')
about+=section('Our approach','Ideas deserve care and clarity.','<p class="lead">Whether you’re celebrating a moment, ordering a personalized piece, or getting your business online, we focus on the details that make the result feel like yours.</p><p>We bring creativity, communication, and a thoughtful process to projects for individuals, events, and businesses.</p>'+a('/contact/','Connect with us'))
about+=section('What we do','One brand. Two creative directions.',cards([card('Products','Custom apparel, gifts, event pieces, and digital categories.',a('/shop/','Explore products')),card('Personalization','A direct request path when your idea calls for your own details.',a(L['custom'],'Start a request')),card('Business services','Websites, Shopify and Etsy support, listings, and more.',a('/services/','Explore services'))]),'light')
page('about/','About Everyday Essentials','Meet Everyday Essentials, a woman-owned DFW creative business for individuals, events, and growing businesses.',about)
contact=hero('Contact','Let’s talk about your idea.','Choose the right form so we can get the details we need to help.')
contact+=section('Get started','The right place for your project.',cards([card('Custom products','Apparel, event pieces, memorial products, and personalized gifts.',a(L['custom'],'Request a Custom Order')),card('Business services','Website design, redesign, Shopify, Etsy, and listings.',a(L['inquiry'],'Get Started')),card('Business partnerships','Tell us about a collaboration or business project.',a(L['inquiry'],'Discuss a partnership'))]))
contact+=section('Keep in touch','Follow the creative process.',a(L['instagram'],'Instagram ↗'),'dark')
page('contact/','Contact & Partnerships','Contact Everyday Essentials for custom orders, business services, and partnership inquiries.',contact)
faqs=[('Where can I shop products?','Choose a collection on the Shop page. Working category links open Payhip for browsing and checkout; pending categories are clearly marked.'),('How do I request a custom order?','Send the details through the Custom Order Request form and we’ll follow up about the quote and next steps.'),('How do business service payments work?','A 50% deposit is due to begin and the remaining 50% is due before final launch and ownership transfer.'),('When does the timeline begin?','After required payment, content, photos, business information, and account details have been received.'),('How many revisions are included?','Revision rounds depend on the package. Out-of-scope additions may need a new quote.'),('What does the 14-day correction period cover?','For 14 calendar days after launch, technical issues with the originally delivered website are corrected, including broken links, layout issues, form errors, and delivered features that do not work. New content, pages, redesigns, features, client-made or third-party changes, and later-caused issues are excluded.'),('Are Shopify fees included?','No. Shopify subscription fees, domain costs, paid apps, payment-processing fees, and other third-party fees are paid directly by the client.')]
faq=hero('FAQ & policies','Good to know before we begin.','Answers about shopping, custom requests, and business services.')
faq+=section('Your questions','Helpful details in one place.','<div class="faq">'+''.join('<details><summary>'+q+'</summary><p>'+v+'</p></details>' for q,v in faqs)+'</div>','light')
page('faq/','FAQ & Service Policies','Answers about shopping, deposits, timelines, revisions, Shopify fees, and the launch correction period.',faq)
clients=hero('Current clients','Your project links, all in one place.','Use these forms when they apply to your active website project.')
clients+=section('Project workflow','Continue your website project.',cards([card('Website Client Onboarding','Share the details and assets needed to begin.',a(L['onboarding'],'Open onboarding')),card('Website Review & Approval','Review your project and submit feedback or approval.',a(L['approval'],'Open review form'))]))
page('current-clients/','Current Clients','Website onboarding and review forms for existing Everyday Essentials clients.',clients)
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+html.escape(absolute(p))+'</loc></url>' for p in ['','shop/','shop/bundles/','shop/graduation-bundles/','custom-orders/','services/','services/websites/','services/seo/','services/shopify/','services/etsy/','services/payhip/','services/add-ons/','about/','contact/','faq/','current-clients/'] if SITE_ORIGIN)+'</urlset>')
(R/'robots.txt').write_text('User-agent: *\nAllow: /\n'+('Sitemap: '+absolute('sitemap.xml')+'\n' if SITE_ORIGIN else ''))
(R/'_headers').write_text('/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n')
